---
title: "Welcome to One-carat Blog!"
description: |
  Welcome to One-carat Blog! I hope you enjoy 
  my blog.
author:
  - name: Jewel Johnson 
    url: https://jeweljohnsonj.github.io/jeweljohnson.github.io/
date: 12-17-2021
output:
  distill::distill_article:
    self_contained: false
preview: proud_of_you.gif
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Making of One-carat Blog

My name is Jewel Johnson and this is my story of how this blog was created. I wanted to have a space to share what I learned over time and that was one of the main reasons behind creating this blog. I will mostly write science articles that are focused on making complex information available to the public. Science communication is very important as it helps in making the public well informed about the advances in science. I am also an R enthusiast and therefore I will also be writing about R programming in this blog. I have already made tutorials describing how to use `ggplot2`, `tidyr` and `dplyr` packages in R for beginners. Overall this blog is still in its infancy and there is a lot of work to be done.

## How was this blog made?

I never thought that I will be making this blog when I started my venture to write science articles. Initially, I thought I will write articles on medium.com. But soon I scrapped that idea for two main reasons. The first reason was that The Medium is a paid and subscription-based service which will limit the reach of my articles. Most articles in the medium are mediocre and filled with click baits and is a waste of time. When I looked at some of the R programming articles in medium, most of them are plagiarized from the r-package websites and other tutorial websites. The second reason was medium is not a platform for writing coding oriented articles. There is syntax support for programming languages and it is cumbersome to work with it. These reasons swayed me to look for alternatives. 

The first choice was 'blogger' from Google, but again it was not an elegant solution. That is when I learned about markdown files and how you can build a website with them. Now a website or blog needs three things for it to work. It needs a hosting service, a domain address and content. You can always make content on your own, it is limited by the creator. But you will be mostly spending money on hosting services for physical storage and a domain address for making your website available online. Now money is a problem for me, at least right now. So this is when I learned that you can host your website using GitHub, which was just amazing.

So my journey began from using markdown and GitHub. But again markdown was not a very good choice for coding oriented articles. Also since I use R it is just cumbersome to copy-paste both the code as well as its output each and whenever I write some R code. But again all was not lost. From 'markdown', I began my journey to 'Rmarkdown'. Now Rmarkdown was everything I wanted to have. So I had made my first website using the `Rmarkdown` package in R and hosted it in GitHub. But again as you get to know something well you will also understand its limitations. Rmarkdown is an easy to use package which can be used to make amazing pdf and HTML pages. But it had its limitations in customisations and other features. So after some research, I found two other packages in R which can serve my goal. 

The first was the `distill` package in R. Now coming from Rmakrdown to distill I soon began to appreciate its features. Distill is like the savvy sibling of Rmarkdown, which offered a lot of features out of the box and had an active developer community. The second package I learned about was `blogdown`. Now, blogdown has everything you can ask for while making a website. The websites created using the blogdown package was top-notch and professional but it was heavily dependent on a third-party service called `Hugothemes`. This made me select `distill` over `blogdown` and I have been enjoying the distill package very much. Also distill was first published just two years ago. It has miles to go in terms of improvements but has high potential. I began learning about distill package on Nov 26, 2021, and since then I have been working on improving my blog using it. I want to thank the wonderful team behind the development of the `distill` r-package and I also offer my gratitude to `GitHub` which is offering free hosting services which I am sure is very helpful to students like me.   

## My vision

I want to use this blog to showcase my skills and promote science communication. I will be writing about some amazing research and advancements in the science community. I am confident that the skillet I garnered overtime for these efforts will surely help me for PhD in the future. With that, I warmly welcome you to my blog and I hope you have as much fun reading these articles, as I had while creating these articles. If you find some articles helpful and you can share them with your friends who might enjoy them as much as you did. This blog has no ads so it is a perfect place for reading. I will strive to put forward high-quality articles as I respect your time as a reader. Thanks for visiting and I wish you the best!





